sudo: false
language: ruby
rvm:
  - 2.4
addons:
  apt:
    packages:
      - lftp
script:
  - bundle exec jekyll build
  - lftp -c "set sftp:auto-confirm yes ; open -u $DEPLOY_USER,$DEPLOY_PASS sftp://$DEPLOY_HOST ; mirror -R -e _site $DEPLOY_PATH ; quit"
