sudo: false
language: ruby
rvm:
  - 2.7
addons:
  apt:
    packages:
      - lftp
script:
  - bundle exec jekyll build
  - lftp -e "mirror -R -e _site $DEPLOY_PATH; quit" -u $DEPLOY_USER,$DEPLOY_PASS sftp://$DEPLOY_HOST
