title       : SETIN S.r.l.
description : Realizzazione Geoportali Comunali e servizi di elaborazione cartografica, rilievo e rappresentazione del territorio per Enti e Professionisti.
url         : https://www.setin.srl
author      : Gaspare Sganga - http://gasparesganga.com
markdown    : kramdown
kramdown    :
  input : GFM

include : 
  - .htaccess
  - _pages
exclude :
  - browserslist
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

gems :
  - jekyll-assets
  - autoprefixer-rails
  - uglifier

assets : 
  assets    : ["[^_]*"]
  sources   : [_assets]
  prefix    : /assets
  cache     : false
  digest    : true
  compress  :
    js                  : true
    css                 : true
  features:
    automatic_img_size  : false
    automatic_img_alt   : true
    liquid              : false
    integrity           : false